### ISSUE TITLE
How do you show the message tray when you want to see it?

### ISSUE THREAD

**Issue by najamelan** [tuxor1337/insensitive-message-tray#4]
Hi, 

I'm really looking for something like this, because it drives me crazy 10 times a day that I'm typing and the mouse slides of something and it steals the focus.

On the other hand, sometimes I do want to see the message tray. Is this possible with this extension? 

Ideally I would let it pop up much like the windows autohide task bars did, just on top of the screen, without stealing focus (so you can keep typing), without darkening or moving the screen, but I would be happy to press a button to see it, or see it on the applications window, but I don't want to install something that might make it completely inaccessible.

**Comment by tuxor1337** [comment]
Mod+M is the shortcut for the message tray. You regain focus once the message tray disappears again after pressing this shortcut.

**Comment by najamelan** [comment]
Hi, 

that sounds great. Thanks. I tried to install it, but I don't manage. When I run gnome-shell-extension-tool it tells me that the extension is now enabled, but the message tray still does it's havoc. It's not showing up in the list of tweak tool either. Running gnome-shell-extension-tool again just tells me that it's already enabled.

When I try to install it from the gnome extensions website, it's as if it installs, and then when refreshing the page it shows the slider "Off" again...

I'm on debian testing. My version of gnome-shell is 3.8.4-8.

Do you have any idea how to solve this?

**Comment by tuxor1337** [comment]
Maybe, that's an incompatibility with Gnome 3.8. I haven't been doing any 3.8 testing for a long while now, since I'm running 3.10 and some users reported about the behaviour in 3.12. However, at the moment, I can't think of anything particular that might break 3.8 compatibility. Would you please post the error output from lookingglass (Alt+F2, type in 'lg' and Return, then switch to the extensions tab and look for errors)?

**Comment by najamelan** [comment]
It never shows up in looking glass. And lg is modal, so I can't turn it on while having it open. When using the command line to disable it, when I re-enable it, it tells me it is already enabled.

**Comment by tuxor1337** [comment]
Okay, that's strange.

**Comment by najamelan** [comment]
I had to restart my computer before the extension became effective and visible in gnome tweak tools.
