### ISSUE TITLE
Doesn't work completely

### ISSUE THREAD

**Issue by fa7ad** [tuxor1337/insensitive-message-tray#7]
Hi I'm using Ubuntu Utopic + GNOME 3.14.3,
I used this extension without any problems until a few days ago, since that update the extension is not working as expected.
Say If I drag my cursor to the bottom of the screen, the message tray does not open, but if I drag it to Bottom-Left or Bottom-Right corner of the screen, the message tray pops up.
Any solutions to this?

**Comment by tuxor1337** [comment]
I cannot reproduce this on Fedora 21 with GNOME 3.14.3 ...

Do you run other extensions that might conflict with insensitive-message-tray?

**Comment by fa7ad** [comment]
As far as I know, only Simple dock has the same feature and I looked into Simple Dock's source code it uses the exact same code.
I tried commenting that out, the problem persists.
Would you like, say, a video demonstration of the bug?

**Comment by fastrizwaan** [comment]
Same with me on Fedora 21 Workstation, I have top icons, simple dock and insensitive message tray. 

The Left and Right side becomes sensitive (tray pops up from left or right bottom sides)

**Comment by fastrizwaan** [comment]
![screenshot from 2015-01-23 00 02 14](https://cloud.githubusercontent.com/assets/1161682/5861843/2201601a-a293-11e4-904b-ca00a00c45b3.png)

Disabling the Adapt Messagebar and notification in simple dock extension fixes this issue.

**Comment by fa7ad** [comment]
I fixed it (well kinda just a workaround). 
Open the source code for simple dock and comment out section that start and end with >>Message tray<<

**Comment by fa7ad** [comment]
That seems to work for my fc21 machine (removed ubuntu :p )

**Comment by fa7ad** [comment]
For me switching the option off didn't help, so i took the hard path :laughing:

**Comment by tuxor1337** [comment]
So, can this issue be closed?

**Comment by fa7ad** [comment]
I suppose, most likely a fault on Simple Dock's end
/closed
